// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: control.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LayerPair struct {
	OldDigest            string   `protobuf:"bytes,1,opt,name=old_digest,json=oldDigest,proto3" json:"old_digest,omitempty"`
	NewDigest            string   `protobuf:"bytes,2,opt,name=new_digest,json=newDigest,proto3" json:"new_digest,omitempty"`
	NewTocDigest         string   `protobuf:"bytes,3,opt,name=new_toc_digest,json=newTocDigest,proto3" json:"new_toc_digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LayerPair) Reset()         { *m = LayerPair{} }
func (m *LayerPair) String() string { return proto.CompactTextString(m) }
func (*LayerPair) ProtoMessage()    {}
func (*LayerPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{0}
}
func (m *LayerPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayerPair.Unmarshal(m, b)
}
func (m *LayerPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayerPair.Marshal(b, m, deterministic)
}
func (m *LayerPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayerPair.Merge(m, src)
}
func (m *LayerPair) XXX_Size() int {
	return xxx_messageInfo_LayerPair.Size(m)
}
func (m *LayerPair) XXX_DiscardUnknown() {
	xxx_messageInfo_LayerPair.DiscardUnknown(m)
}

var xxx_messageInfo_LayerPair proto.InternalMessageInfo

func (m *LayerPair) GetOldDigest() string {
	if m != nil {
		return m.OldDigest
	}
	return ""
}

func (m *LayerPair) GetNewDigest() string {
	if m != nil {
		return m.NewDigest
	}
	return ""
}

func (m *LayerPair) GetNewTocDigest() string {
	if m != nil {
		return m.NewTocDigest
	}
	return ""
}

type RefreshImageRequest struct {
	Pairs                []*LayerPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	WithBackgroundFetch  bool         `protobuf:"varint,2,opt,name=with_background_fetch,json=withBackgroundFetch,proto3" json:"with_background_fetch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RefreshImageRequest) Reset()         { *m = RefreshImageRequest{} }
func (m *RefreshImageRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshImageRequest) ProtoMessage()    {}
func (*RefreshImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{1}
}
func (m *RefreshImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshImageRequest.Unmarshal(m, b)
}
func (m *RefreshImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshImageRequest.Marshal(b, m, deterministic)
}
func (m *RefreshImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshImageRequest.Merge(m, src)
}
func (m *RefreshImageRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshImageRequest.Size(m)
}
func (m *RefreshImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshImageRequest proto.InternalMessageInfo

func (m *RefreshImageRequest) GetPairs() []*LayerPair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *RefreshImageRequest) GetWithBackgroundFetch() bool {
	if m != nil {
		return m.WithBackgroundFetch
	}
	return false
}

type LayerResult struct {
	OldDigest string `protobuf:"bytes,1,opt,name=old_digest,json=oldDigest,proto3" json:"old_digest,omitempty"`
	NewDigest string `protobuf:"bytes,2,opt,name=new_digest,json=newDigest,proto3" json:"new_digest,omitempty"`
	// Empty on success; populated with the failure reason otherwise.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// True when the per-layer refresh fell back to whole-layer invalidation
	// instead of applying chunk-level deltas. Triggered when the old and new
	// TOCs cannot be aligned chunk-for-chunk: entry count differs, a metadata
	// id is present on only one side, walk order shifted (same id maps to a
	// different (parent, name)), or any chunk lacks a ChunkDigest.
	Fallback             bool     `protobuf:"varint,4,opt,name=fallback,proto3" json:"fallback,omitempty"`
	ChangedChunks        int64    `protobuf:"varint,5,opt,name=changed_chunks,json=changedChunks,proto3" json:"changed_chunks,omitempty"`
	AddedChunks          int64    `protobuf:"varint,6,opt,name=added_chunks,json=addedChunks,proto3" json:"added_chunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LayerResult) Reset()         { *m = LayerResult{} }
func (m *LayerResult) String() string { return proto.CompactTextString(m) }
func (*LayerResult) ProtoMessage()    {}
func (*LayerResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{2}
}
func (m *LayerResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayerResult.Unmarshal(m, b)
}
func (m *LayerResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayerResult.Marshal(b, m, deterministic)
}
func (m *LayerResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayerResult.Merge(m, src)
}
func (m *LayerResult) XXX_Size() int {
	return xxx_messageInfo_LayerResult.Size(m)
}
func (m *LayerResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LayerResult.DiscardUnknown(m)
}

var xxx_messageInfo_LayerResult proto.InternalMessageInfo

func (m *LayerResult) GetOldDigest() string {
	if m != nil {
		return m.OldDigest
	}
	return ""
}

func (m *LayerResult) GetNewDigest() string {
	if m != nil {
		return m.NewDigest
	}
	return ""
}

func (m *LayerResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LayerResult) GetFallback() bool {
	if m != nil {
		return m.Fallback
	}
	return false
}

func (m *LayerResult) GetChangedChunks() int64 {
	if m != nil {
		return m.ChangedChunks
	}
	return 0
}

func (m *LayerResult) GetAddedChunks() int64 {
	if m != nil {
		return m.AddedChunks
	}
	return 0
}

type RefreshImageResponse struct {
	Results              []*LayerResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RefreshImageResponse) Reset()         { *m = RefreshImageResponse{} }
func (m *RefreshImageResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshImageResponse) ProtoMessage()    {}
func (*RefreshImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{3}
}
func (m *RefreshImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshImageResponse.Unmarshal(m, b)
}
func (m *RefreshImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshImageResponse.Marshal(b, m, deterministic)
}
func (m *RefreshImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshImageResponse.Merge(m, src)
}
func (m *RefreshImageResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshImageResponse.Size(m)
}
func (m *RefreshImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshImageResponse proto.InternalMessageInfo

func (m *RefreshImageResponse) GetResults() []*LayerResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*LayerPair)(nil), "LayerPair")
	proto.RegisterType((*RefreshImageRequest)(nil), "RefreshImageRequest")
	proto.RegisterType((*LayerResult)(nil), "LayerResult")
	proto.RegisterType((*RefreshImageResponse)(nil), "RefreshImageResponse")
}

func init() { proto.RegisterFile("control.proto", fileDescriptor_0c5120591600887d) }

var fileDescriptor_0c5120591600887d = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x6b, 0xe2, 0x40,
	0x18, 0xc6, 0xc9, 0xba, 0xba, 0xfa, 0x1a, 0x3d, 0x8c, 0x0a, 0x41, 0x58, 0xc8, 0x66, 0xd7, 0xc5,
	0xcb, 0x46, 0x70, 0x8f, 0x85, 0x1e, 0xb4, 0x14, 0x0a, 0x1e, 0xca, 0xb4, 0xa7, 0x5e, 0xc2, 0x64,
	0x32, 0xf9, 0x83, 0x71, 0x26, 0x9d, 0x99, 0x10, 0xda, 0x2f, 0xd8, 0xaf, 0x55, 0x32, 0x31, 0xd6,
	0x82, 0xb7, 0x1e, 0xe7, 0xf9, 0x3d, 0x79, 0xf3, 0x3c, 0xf3, 0x0e, 0x8c, 0xa8, 0xe0, 0x5a, 0x8a,
	0xdc, 0x2f, 0xa4, 0xd0, 0xc2, 0x13, 0x30, 0xd8, 0x91, 0x17, 0x26, 0xef, 0x49, 0x26, 0xd1, 0x4f,
	0x00, 0x91, 0x47, 0x41, 0x94, 0x25, 0x4c, 0x69, 0xc7, 0x72, 0xad, 0xe5, 0x00, 0x0f, 0x44, 0x1e,
	0xdd, 0x18, 0xa1, 0xc6, 0x9c, 0x55, 0x2d, 0xfe, 0xd6, 0x60, 0xce, 0xaa, 0x23, 0xfe, 0x03, 0xe3,
	0x1a, 0x6b, 0x41, 0x5b, 0x4b, 0xc7, 0x58, 0x6c, 0xce, 0xaa, 0x47, 0x41, 0x1b, 0x97, 0xb7, 0x87,
	0x09, 0x66, 0xb1, 0x64, 0x2a, 0xbd, 0x3b, 0x90, 0x84, 0x61, 0xf6, 0x5c, 0xd6, 0x1f, 0xbb, 0xd0,
	0x2d, 0x48, 0x26, 0x95, 0x63, 0xb9, 0x9d, 0xe5, 0x70, 0x0d, 0xfe, 0x29, 0x15, 0x6e, 0x00, 0x5a,
	0xc3, 0xac, 0xca, 0x74, 0x1a, 0x84, 0x84, 0xee, 0x13, 0x29, 0x4a, 0x1e, 0x05, 0x31, 0xd3, 0x34,
	0x35, 0x41, 0xfa, 0x78, 0x52, 0xc3, 0xcd, 0x89, 0xdd, 0xd6, 0xc8, 0x7b, 0xb3, 0x60, 0x68, 0x06,
	0x61, 0xa6, 0xca, 0x5c, 0x7f, 0xb1, 0xe0, 0x14, 0xba, 0x4c, 0x4a, 0x21, 0x8f, 0xbd, 0x9a, 0x03,
	0x9a, 0x43, 0x3f, 0x26, 0x79, 0x5e, 0xc7, 0x72, 0xbe, 0x9b, 0x28, 0xa7, 0x33, 0x5a, 0xc0, 0x98,
	0xa6, 0x84, 0x27, 0x2c, 0x0a, 0x68, 0x5a, 0xf2, 0xbd, 0x72, 0xba, 0xae, 0xb5, 0xec, 0xe0, 0xd1,
	0x51, 0xdd, 0x1a, 0x11, 0xfd, 0x02, 0x9b, 0x44, 0xd1, 0x87, 0xa9, 0x67, 0x4c, 0x43, 0xa3, 0x35,
	0x16, 0xef, 0x1a, 0xa6, 0x9f, 0xaf, 0x4d, 0x15, 0x82, 0x2b, 0x86, 0xfe, 0xc2, 0x0f, 0x69, 0xba,
	0xb5, 0x37, 0x67, 0xfb, 0x67, 0x85, 0x71, 0x0b, 0xd7, 0x3b, 0x18, 0x3d, 0x68, 0x22, 0x93, 0xd7,
	0x6d, 0xb3, 0x7e, 0x74, 0x05, 0xf6, 0xf9, 0x40, 0x34, 0xf5, 0x2f, 0xac, 0x65, 0x3e, 0xf3, 0x2f,
	0xfd, 0x75, 0xb3, 0x78, 0xfa, 0x9d, 0x64, 0x3a, 0x2d, 0x43, 0x9f, 0x8a, 0xc3, 0x4a, 0x99, 0xc1,
	0xff, 0x14, 0x27, 0x85, 0x4a, 0x85, 0xd6, 0x4c, 0xae, 0x62, 0xb5, 0x2a, 0xc2, 0xb0, 0x67, 0xde,
	0xd8, 0xff, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xe3, 0x23, 0x7b, 0x74, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StargzControlClient is the client API for StargzControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StargzControlClient interface {
	RefreshImage(ctx context.Context, in *RefreshImageRequest, opts ...grpc.CallOption) (*RefreshImageResponse, error)
}

type stargzControlClient struct {
	cc *grpc.ClientConn
}

func NewStargzControlClient(cc *grpc.ClientConn) StargzControlClient {
	return &stargzControlClient{cc}
}

func (c *stargzControlClient) RefreshImage(ctx context.Context, in *RefreshImageRequest, opts ...grpc.CallOption) (*RefreshImageResponse, error) {
	out := new(RefreshImageResponse)
	err := c.cc.Invoke(ctx, "/StargzControl/RefreshImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StargzControlServer is the server API for StargzControl service.
type StargzControlServer interface {
	RefreshImage(context.Context, *RefreshImageRequest) (*RefreshImageResponse, error)
}

// UnimplementedStargzControlServer can be embedded to have forward compatible implementations.
type UnimplementedStargzControlServer struct {
}

func (*UnimplementedStargzControlServer) RefreshImage(ctx context.Context, req *RefreshImageRequest) (*RefreshImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshImage not implemented")
}

func RegisterStargzControlServer(s *grpc.Server, srv StargzControlServer) {
	s.RegisterService(&_StargzControl_serviceDesc, srv)
}

func _StargzControl_RefreshImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StargzControlServer).RefreshImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StargzControl/RefreshImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StargzControlServer).RefreshImage(ctx, req.(*RefreshImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StargzControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StargzControl",
	HandlerType: (*StargzControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshImage",
			Handler:    _StargzControl_RefreshImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
