// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: control.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RefreshLayerRequest struct {
	OldDigest            string   `protobuf:"bytes,1,opt,name=old_digest,json=oldDigest,proto3" json:"old_digest,omitempty"`
	NewDigest            string   `protobuf:"bytes,2,opt,name=new_digest,json=newDigest,proto3" json:"new_digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshLayerRequest) Reset()         { *m = RefreshLayerRequest{} }
func (m *RefreshLayerRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshLayerRequest) ProtoMessage()    {}
func (m *RefreshLayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshLayerRequest.Unmarshal(m, b)
}
func (m *RefreshLayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshLayerRequest.Marshal(b, m, deterministic)
}
func (m *RefreshLayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshLayerRequest.Merge(m, src)
}
func (m *RefreshLayerRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshLayerRequest.Size(m)
}
func (m *RefreshLayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshLayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshLayerRequest proto.InternalMessageInfo

func (m *RefreshLayerRequest) GetOldDigest() string {
	if m != nil {
		return m.OldDigest
	}
	return ""
}

func (m *RefreshLayerRequest) GetNewDigest() string {
	if m != nil {
		return m.NewDigest
	}
	return ""
}

type RefreshLayerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshLayerResponse) Reset()         { *m = RefreshLayerResponse{} }
func (m *RefreshLayerResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshLayerResponse) ProtoMessage()    {}
func (m *RefreshLayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshLayerResponse.Unmarshal(m, b)
}
func (m *RefreshLayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshLayerResponse.Marshal(b, m, deterministic)
}
func (m *RefreshLayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshLayerResponse.Merge(m, src)
}
func (m *RefreshLayerResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshLayerResponse.Size(m)
}
func (m *RefreshLayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshLayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshLayerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RefreshLayerRequest)(nil), "RefreshLayerRequest")
	proto.RegisterType((*RefreshLayerResponse)(nil), "RefreshLayerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StargzControlClient is the client API for StargzControl service.
type StargzControlClient interface {
	RefreshLayer(ctx context.Context, in *RefreshLayerRequest, opts ...grpc.CallOption) (*RefreshLayerResponse, error)
}

type stargzControlClient struct {
	cc *grpc.ClientConn
}

func NewStargzControlClient(cc *grpc.ClientConn) StargzControlClient {
	return &stargzControlClient{cc}
}

func (c *stargzControlClient) RefreshLayer(ctx context.Context, in *RefreshLayerRequest, opts ...grpc.CallOption) (*RefreshLayerResponse, error) {
	out := new(RefreshLayerResponse)
	err := c.cc.Invoke(ctx, "/StargzControl/RefreshLayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StargzControlServer is the server API for StargzControl service.
type StargzControlServer interface {
	RefreshLayer(context.Context, *RefreshLayerRequest) (*RefreshLayerResponse, error)
}

// UnimplementedStargzControlServer can be embedded to have forward compatible implementations.
type UnimplementedStargzControlServer struct {
}

func (*UnimplementedStargzControlServer) RefreshLayer(ctx context.Context, req *RefreshLayerRequest) (*RefreshLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshLayer not implemented")
}

func RegisterStargzControlServer(s *grpc.Server, srv StargzControlServer) {
	s.RegisterService(&_StargzControl_serviceDesc, srv)
}

func _StargzControl_RefreshLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StargzControlServer).RefreshLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StargzControl/RefreshLayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StargzControlServer).RefreshLayer(ctx, req.(*RefreshLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StargzControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StargzControl",
	HandlerType: (*StargzControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshLayer",
			Handler:    _StargzControl_RefreshLayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
